version: '3.9'

services:

  postgres:
    image: postgres_example
    environment:
      POSTGRES_DB: exampledb
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    
    environment:
      PGADMIN_DEFAULT_EMAIL: example@mail.net
      PGADMIN_DEFAULT_PASSWORD: examplepass
    ports:
      - "5050:80"

volumes:
  postgres-data: